services:
  demo1:
    build: .
    command: flask --app app run --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
  demo2:
    build: .
    command: gunicorn -b 0.0.0.0:8000 "app:create_app()"
    ports:
      - 8002:8000
