# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2022]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools==57.5.0
        pip install -r dev-requirement.txt
        pip install .

    - name: Lint with flake8
      run: |
        # Run flake8 on Python files
        flake8 pyencrypt --count --show-source --max-complexity=10 --statistics
        # Run flake8 on test files
        flake8 tests --count --show-source --max-complexity=10 --statistics --ignore F401,W503

    - name: Test with pytest
      run: |
        pytest
